### ISSUE TITLE
Error in Cron error while executing mailchimp_clear_ecommerce_data

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1112]
Using latest released version. Error in Cron error while executing mailchimp_clear_ecommerce_data

Problem: As a result the cleaning is not working

Also : I dont know if this auto solves itself or that MC now thinks the table is alreadys cleansed (which it is not)

See the image: there are empty related_ids in the IN clause ... resulting in an error where two commas are present

The related_ids should be checked for emptiness before adding it to the IN statement

or there might be an error somewhere else because the relatd_ids should not be empty?

![image](https://user-images.githubusercontent.com/652395/69039269-e14b6280-09eb-11ea-9f0e-35d2166e2dac.png)

```
Cron error while executing mailchimp_clear_ecommerce_data:

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 71853, 71853, 71853, 76857, 76857, 77022, 81711, 21076, 21077, 21078, 21079, 21' at line 1 in /lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `ma...', Array)
#5 /lib/Varien/Db/Adapter/Pdo/Mysql.php(508): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `ma...', Array)
#6 /lib/Zend/Db/Adapter/Abstract.php(664): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `ma...')
#7 /app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php(293): Zend_Db_Adapter_Abstract->delete('mailchimp_ecomm...', '(related_id IN ...')
#8 /app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php(91): Ebizmarts_MailChimp_Model_ClearEcommerce->deleteEcommerceRows('25, 27, 29, 34,...', 'PRO')
#9 /app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php(69): Ebizmarts_MailChimp_Model_ClearEcommerce->processData(Array, 'PRO')
#10 /app/code/community/Ebizmarts/MailChimp/Model/Cron.php(51): Ebizmarts_MailChimp_Model_ClearEcommerce->clearEcommerceData()
#11 /app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->clearEcommerceData(Object(Aoe_Scheduler_Model_Schedule))
#12 /app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#13 /app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#14 /app/code/local/Xtento/StockImport/Model/Observer/Cron/Config.php(24): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#15 /app/code/core/Mage/Core/Model/App.php(1365): Xtento_StockImport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))
#16 /app/code/core/Mage/Core/Model/App.php(1338): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_StockImport_Model_Observer_Cron_Config), 'addCronjobsToCo...', Object(Varien_Event_Observer))
#17 /app/Mage.php(467): Mage_Core_Model_App->dispatchEvent('default', Array)
#18 /cron.php(81): Mage::dispatchEvent('default')
#19 {main}

Next Zend_Db_Statement_Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 71853, 71853, 71853, 76857, 76857, 77022, 81711, 21076, 21077, 21078, 21079, 21' at line 1, query was: DELETE FROM `mailchimp_ecommerce_sync_data` WHERE (related_id IN (25, 27, 29, 34, 40, 56, 57, 63, 69, 75, 76, 84, 88, 99, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, , 71853, 71853, 71853, 76857, 76857, 77022, 81711, 21076, 21077, 21078, 21079, 21080, 22486, 22487, 84567, 22486, 22487, , 85217, 85217, 85217, 85398, 85398, 85398, 86033, 86033, 86033, 88262, 88262, 88263, 88263, 88262, 88263, 21076, 21077, 21078, 21079, 21080, 88376, 88376, 88605, 88605, 88605, 88706, 88706, 88706, 21076, 21077, 21078, 21079, 21080, 22486, 21076, 21077, 21078, 21079, 21080, 21076, 21077, 21078, 21079, 21080, 21076, 21077, 21078, 21079, 21080, 21076, 21077, 21078, 21079, 21080, 22486, 22486, 22486, 22486, 93377, 93377, 93377, 21076, 21077, 21078, 21079, 21080, 22486, 22487, 21076, 21077, 21078, 21079, 21080, 22486, 22487, 94667, 94667, 94667, 94667, 94667, 94667)) AND (type = 'PRO') in /lib/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `ma...', Array)
#4 /lib/Varien/Db/Adapter/Pdo/Mysql.php(508): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `ma...', Array)
#5 /lib/Zend/Db/Adapter/Abstract.php(664): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `ma...')
#6 /app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php(293): Zend_Db_Adapter_Abstract->delete('mailchimp_ecomm...', '(related_id IN ...')
#7 /app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php(91): Ebizmarts_MailChimp_Model_ClearEcommerce->deleteEcommerceRows('25, 27, 29, 34,...', 'PRO')
#8 /app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php(69): Ebizmarts_MailChimp_Model_ClearEcommerce->processData(Array, 'PRO')
#9 /app/code/community/Ebizmarts/MailChimp/Model/Cron.php(51): Ebizmarts_MailChimp_Model_ClearEcommerce->clearEcommerceData()
#10 /app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->clearEcommerceData(Object(Aoe_Scheduler_Model_Schedule))
#11 /app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#12 /app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#13 /app/code/local/Xtento/StockImport/Model/Observer/Cron/Config.php(24): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#14 /app/code/core/Mage/Core/Model/App.php(1365): Xtento_StockImport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))
#15 /app/code/core/Mage/Core/Model/App.php(1338): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_StockImport_Model_Observer_Cron_Config), 'addCronjobsToCo...', Object(Varien_Event_Observer))
#16 /app/Mage.php(467): Mage_Core_Model_App->dispatchEvent('default', Array)
#17 /cron.php(81): Mage::dispatchEvent('default')
#18 {main}
```

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
Please remember to follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) as we need to know in what Magento and Mailchimp versions this happens.
Saying "latest" does not work for us as new versions are released constantly and many times people don't realize there is a newer version than the one they got.

Also it helps us to try to replicate the problem.

Regards.

**Comment by seansan** [comment]
Thanks!

We followed these rules. And yes I took the time to report it!! hurrah!!

Expected result is clear I think. Versions is as I said : latest of all (to
date)

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
Do you mean 1.1.18 official release?

Regards,

**Comment by giorello** [comment]
This would prevent this issue, but we should investigate the origin of those empty ids; We suspect of a wrong DB join. 
We will merge your change but keep this issue open to work/investigate the full issue.

Thanks

Regards, 
Javier Giorello.

**Comment by seansan** [comment]
Thanks
We only use official naturally
https://github.com/mailchimp/mc-magento/releases/tag/1.1.18
M 1.9.4.x
Patch supplied was already merges I saw
Issue maybe keep open to investigate how empty ids can exist

**Comment by Santiagoebizmarts** [comment]
The behavior of the ecommerce data item save has been redone, please test this in the incoming release 1.1.19. If it happens again we can reopen.
