### ISSUE TITLE
Save Product Issue

### ISSUE THREAD

**Issue by postadelmaga** [mailchimp/mc-magento#188]
After installing version 1.1.6 we are not able to save product anymore, log shows the following problem.

We tracked down the issue to the functionality Ecommerce integration (_system->config->mailchimp->Ecommerce_), disabling it we are now able to save the product again.

```
2017-04-05T07:53:41+00:00 ERR (3): 
exception 'Mage_Eav_Model_Entity_Attribute_Exception' in /var/www/clients/client2/web4/web/app/code/core/Mage/Core/Model/Config.php:1354
Stack trace:
#0 /var/www/clients/client2/web4/web/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('eav/entity_attr...', '')
#1 /var/www/clients/client2/web4/web/app/code/core/Mage/Eav/Model/Entity/Abstract.php(661): Mage::getModel('eav/entity_attr...', '')
#2 /var/www/clients/client2/web4/web/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1660): Mage_Eav_Model_Entity_Abstract->walkAttributes('backend/afterSa...', Array)
#3 /var/www/clients/client2/web4/web/app/code/core/Mage/Catalog/Model/Resource/Product.php(195): Mage_Eav_Model_Entity_Abstract->_afterSave(Object(BurnOut_ProductPart_Model_Catalog_Product))
#4 /var/www/clients/client2/web4/web/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1124): Mage_Catalog_Model_Resource_Product->_afterSave(Object(BurnOut_ProductPart_Model_Catalog_Product))
#5 /var/www/clients/client2/web4/web/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(BurnOut_ProductPart_Model_Catalog_Product))
#6 /var/www/clients/client2/web4/web/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(728): Mage_Core_Model_Abstract->save()
#7 /var/www/clients/client2/web4/web/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->saveAction()
#8 /var/www/clients/client2/web4/web/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
#9 /var/www/clients/client2/web4/web/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /var/www/clients/client2/web4/web/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/clients/client2/web4/web/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/clients/client2/web4/web/index.php(90): Mage::run('en', 'store')
#13 {main}
```

**Comment by Santiagoebizmarts** [comment]
Hello @postadelmaga 

I see a BurnOut_ProductPart product object, I suggest you to try disabling that extension and test again to see if the cause is a conflict.

Please read this [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating an issue, it can helps us to have some additional information such as your Magento version.

Regards.

**Comment by postadelmaga** [comment]
The model different because we have extended the default product model but the modification are small so I doubt this is the cause.

Right now we have disabled the extension because my customer plain to use later.
I will update this bug report once we enable again the extension and test it.

Thanks

**Comment by centerax** [comment]
@postadelmaga please test the new version and feel free to comment here and we will reopen.
