### ISSUE TITLE
Error Cron

### ISSUE THREAD

**Issue by henriquemnr** [mailchimp/mc-magento#393]
Hi guys, i'm having this error:

Cron error while executing mailchimp_bulksync_data:

```
exception 'Mage_Core_Exception' with message 'Invalid model/method definition, expecting "model/class::method", got "" instead.' in /app/Mage.php:595
Stack trace:
#0 /app/code/community/Aoe/Scheduler/Helper/Data.php(313): Mage::throwException('Invalid model/m...')
#1 /app/code/community/Aoe/Scheduler/Model/Job.php(145): Aoe_Scheduler_Helper_Data->getCallBack('')
#2 /app/code/community/Aoe/Scheduler/Model/Schedule.php(213): Aoe_Scheduler_Model_Job->getCallback()
#3 /app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#4 /app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#5 /app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#6 /app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#7 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#8 /shell/scheduler.php(519): Mage::dispatchEvent('default', Array)
#9 /shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#10 /shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#11 {main}
```

**Comment by Santiagoebizmarts** [comment]
Hello,

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) and add the missing information in order to allow us to take a look at this problem.

Regards.
