### ISSUE TITLE
unexpected error: Call to protected method Ebizmarts_MailChimp_Model_Api_Products::joinProductAttributes() from context 'Ebizmarts_MailChimp_Helper_Data'

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#529]
unexpected error in logging after upgrade latest version
method is not protected, but public: why this message?
no email lists were deleted

expected: no error, started after upgrade from previous version 1.1.8

actual: errors about cannot access function

```
[03-Oct-2017 12:50:07 UTC] PHP Fatal error:  Uncaught Error: Call to protected method Ebizmarts_MailChimp_Model_Api_Products::joinProductAttributes() from context 'Ebizmarts_MailChimp_Helper_Data' in app/code/community/Ebizmarts/MailChimp/Helper/Data.php:2202
Stack trace:
#0 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2157): Ebizmarts_MailChimp_Helper_Data->isMissingProductLowerThanId('48598', '9')
#1 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2104): Ebizmarts_MailChimp_Helper_Data->isMissingItemLowerThanId('48598', 'PRO', '9')
#2 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2043): Ebizmarts_MailChimp_Helper_Data->allResendItemsSentPerStoreView('9')
#3 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2023): Ebizmarts_MailChimp_Helper_Data->allResendItemsSent('9', 'stores')
#4 app/code/community/Ebizmarts/MailChimp/Helper in app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 2202
```

Split into 2 issues as requested #526 526

**Comment by Santiagoebizmarts** [comment]
Hello,

As the error states the problem is the joinProductAttributes method being protected.
I am not sure why this happens if you have this method set as public. I think there must be something wrong in your installation or cache need to be refreshed.

Regards.
