### ISSUE TITLE
Error Report when Export Orders CSV or Excel

### ISSUE THREAD

**Issue by dimitrilongo** [mailchimp/mc-magento#732]
### Preconditions

On 1.9+ CE
Mailchimp/Mandrill For Magento v1.1.12

### Steps to reproduce

1. Export Orders to excel ou CSV
2.
3.

### Expected result

1. Open File window in order to save export file on your computer

### Actual result

1. Error Report
`````
a:5:{i:0;s:56:"You cannot define a correlation name 'mc' more than once";i:1;s:2508:"#0 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(62159): Zend_Db_Select->_join('left join', Array, 'mc.related_id=m...', Array, NULL)
#1 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(60856): Varien_Db_Select->_join('left join', Array, 'mc.related_id=m...', Array, NULL)
#2 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/Ebizmarts_MailChimp_Model_Observer.php(506): Zend_Db_Select->joinLeft(Array, 'mc.related_id=m...', Array)
#3 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(22242): Ebizmarts_MailChimp_Model_Observer->addColumnToSalesOrderGridCollection(Object(Varien_Event_Observer))
#4 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(22215): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MailChimp_Model_Observer), 'addColumnToSale...', Object(Varien_Event_Observer))
#5 /var/www/vhosts/mywebsite.com/httpdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('sales_order_gri...', Array)
#6 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(33247): Mage::dispatchEvent('sales_order_gri...', Array)
#7 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(32378): Mage_Core_Model_Resource_Db_Collection_Abstract->_beforeLoad()
#8 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/Mage_Adminhtml_Block_Widget_Grid.php(951): Varien_Data_Collection_Db->load()
#9 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/Mage_Adminhtml_Block_Widget_Grid.php(1154): Mage_Adminhtml_Block_Widget_Grid->_exportIterateCollection('_exportExcelIte...', Array)
#10 /var/www/vhosts/mywebsite.com/httpdocs/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(713): Mage_Adminhtml_Block_Widget_Grid->getExcelFile('orders.xml')
#11 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(14287): Mage_Adminhtml_Sales_OrderController->exportExcelAction()
#12 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(18823): Mage_Core_Controller_Varien_Action->dispatch('exportExcel')
#13 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(18353): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 /var/www/vhosts/mywebsite.com/httpdocs/includes/src/__default.php(21249): Mage_Core_Controller_Varien_Front->dispatch()
#15 /var/www/vhosts/mywebsite.com/httpdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#16 /var/www/vhosts/mywebsite.com/httpdocs/index.php(83): Mage::run('', 'store')
#17 {main}";s:3:"url";s:87:"/index.php/admin/sales_order/exportExcel/key/31a67a758995b0e1007ccb17262dcaf2/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
````

**Comment by ebizmarts-keller** [comment]
Hello @dimitrilongo

I was not able to reproduce this on my local installation, I see in the stack trace that the error comes from compiled files.

Can you tell me what you have in line 506 at this moment in **/var/www/vhosts/mywebsite.com/httpdocs/includes/src/Ebizmarts_MailChimp_Model_Observer.php** ?

**Comment by sukiman** [comment]
I get the similar error:
"You cannot define a correlation name 'oe' more than once"

The issue happens in Ebizmarts_MailChimp_Model_Observer::addColumnToSalesOrderGridCollection()

```
public function addColumnToSalesOrderGridCollection(Varien_Event_Observer $observer)
{

	$helper = $this->makeHelper();
	$addColumnConfig = $helper->getMonkeyInGrid(0);
	$ecommEnabledAnyScope = $helper->isEcomSyncDataEnabledInAnyScope();
	if ($ecommEnabledAnyScope && $addColumnConfig) {
		$collection = $observer->getOrderGridCollection();
		$collection->addFilterToMap('store_id', 'main_table.store_id');
		$select = $collection->getSelect();
		$select->joinLeft(array('oe' => $collection->getTable('sales/order')), 'oe.entity_id=main_table.entity_id', array('oe.mailchimp_campaign_id'));
		$adapter = $this->getCoreResource()->getConnection('core_write');
		$select->joinLeft(array('mc' => $collection->getTable('mailchimp/ecommercesyncdata')), $adapter->quoteInto('mc.related_id=main_table.entity_id AND type = ?', Ebizmarts_MailChimp_Model_Config::IS_ORDER), array('mc.mailchimp_synced_flag', 'mc.id'));
		$select->group("main_table.entity_id");
		$direction = Mage::registry('sort_column_dir');
		if ($direction) {
			$collection->addOrder('mc.id', $direction);
			Mage::unregister('sort_column_dir');
		}
	}
}
```

This only happens when the export results more than 1 page (default page size is 1000) because on 2nd page, the collection will dispatch after load again.

Mage_Adminhtml_Block_Widget_Grid::_exportIterateCollection()
```
public function _exportIterateCollection($callback, array $args)
{
	$originalCollection = $this->getCollection();
	$count = null;
	$page  = 1;
	$lPage = null;
	$break = false;

	while ($break !== true) {
		$collection = clone $originalCollection;
		$collection->setPageSize($this->_exportPageSize);
		$collection->setCurPage($page);
		$collection->load();
		if (is_null($count)) {
			$count = $collection->getSize();
			$lPage = $collection->getLastPageNumber();
		}
		if ($lPage == $page) {
			$break = true;
		}
		$page ++;

		foreach ($collection as $item) {
			call_user_func_array(array($this, $callback), array_merge(array($item), $args));
		}
	}
}
```


My current workaround is to add a condition checking if an 'oe' or 'mc' aliases already exists in select.
```
public function addColumnToSalesOrderGridCollection(Varien_Event_Observer $observer)
{

	$helper = $this->makeHelper();
	$addColumnConfig = $helper->getMonkeyInGrid(0);
	$ecommEnabledAnyScope = $helper->isEcomSyncDataEnabledInAnyScope();
	if ($ecommEnabledAnyScope && $addColumnConfig) {
		$collection = $observer->getOrderGridCollection();
		// workaround
		$p = $collection->getSelect()->getPart(Zend_Db_Select::FROM);
		if (array_key_exists('oe', $p) || array_key_exists('mc', $p))
		{
			return;
		}
		// --
		$collection->addFilterToMap('store_id', 'main_table.store_id');
		$select = $collection->getSelect();
		$select->joinLeft(array('oe' => $collection->getTable('sales/order')), 'oe.entity_id=main_table.entity_id', array('oe.mailchimp_campaign_id'));
		$adapter = $this->getCoreResource()->getConnection('core_write');
		$select->joinLeft(array('mc' => $collection->getTable('mailchimp/ecommercesyncdata')), $adapter->quoteInto('mc.related_id=main_table.entity_id AND type = ?', Ebizmarts_MailChimp_Model_Config::IS_ORDER), array('mc.mailchimp_synced_flag', 'mc.id'));
		$select->group("main_table.entity_id");
		$direction = Mage::registry('sort_column_dir');
		if ($direction) {
			$collection->addOrder('mc.id', $direction);
			Mage::unregister('sort_column_dir');
		}
	}
}
```

**Comment by Santiagoebizmarts** [comment]
Hello @sukiman 

Thanks for your information. This information is really helpful and will be used in the solution.

Regards.
