### ISSUE TITLE
Trying to get property of non-object in PromoCodes

### ISSUE THREAD

**Issue by ljay79** [mailchimp/mc-magento#733]
See multiple error logs related to Batch processing but could not yet investigate deeper.

### Preconditions

1. Magento 1.9.3.8 CE
2. PHP7, MySQL 5.6.39
3. Mailchimp4Magento 1.1.12

### Steps to reproduce
Unknown yet, part of cron jobs / batch processing
### Expected result
1. No PHP Notices, No Fatal error

### Actual result
mailchimp_bulksync_ecommerce_data.log
```
[18-Jun-2018 09:10:03 UTC] PHP Notice:  Trying to get property of non-object in /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php on line 344
[18-Jun-2018 09:10:03 UTC] PHP Notice:  Trying to get property of non-object in /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php on line 344
[18-Jun-2018 09:10:03 UTC] PHP Notice:  Trying to get property of non-object in /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php on line 344
[18-Jun-2018 09:10:03 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getAll() on null in /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php:344
Stack trace:
#0 /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php(316): Ebizmarts_MailChimp_Model_Api_PromoCodes->getPromoCodesForRule('113')
#1 /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php(59): Ebizmarts_MailChimp_Model_Api_PromoCodes->deletePromoCodesSyncDataByRule(Object(Ebizmarts_MailChimp_Model_Ecommercesyncdata))
#2 /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php(41): Ebizmarts_MailChimp_Model_Api_PromoRules->_getModifiedAndDeletedPromoRules('943ce37d4e9...')
#3 /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(303): Ebizmarts_MailChimp_Model_Api_PromoRules->createBatchJson('943ce37d4e9...', '3')
#4 /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(200): Ebizmarts_Mail in /www/magento/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php on line 344
```

**Comment by Santiagoebizmarts** [comment]
Hello @ljay79 
This looks like a problem with your library. Make sure the latest version was correctly updated under the **lib/Ebizmarts** folder.
You can contact our support at mailchimp@ebizmarts-desk.zendesk.com for more help.

Regards,
