### ISSUE TITLE
The program fails when set up the extension in one store view and disable another store view leaving the API key in blank 

### ISSUE THREAD

**Issue by luciaebizmarts** [mailchimp/mc-magento#863]
### Preconditions
1. Mailchimp for Magento 1.1.13
2. Magento any version

### Steps to reproduce
1. Enable only one [store view](https://imgur.com/JeTrcm7) to send ecommerce data leaving another [store view](https://imgur.com/G94MJtK) disabled and with the field for the API key in blank. 

### Expected result
1. Everything runs fine without errors.

### Actual result
1. The program fails throwing the next two errors:

```
2019-01-29T14:15:27+00:00 DEBUG (7): Could not connect to MailChimp: Make sure the API Key is correct and there is an internet connection
2019-01-29T14:20:03+00:00 DEBUG (7): #0 /home/lucia/www/m1Developer/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(236): Ebizmarts_MailChimp_Helper_Data->getApi('1')
#1 /home/lucia/www/m1Developer/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(200): Ebizmarts_MailChimp_Model_Api_Batches->_ping('1')
#2 /home/lucia/www/m1Developer/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Cron.php(28): Ebizmarts_MailChimp_Model_Api_Batches->handleEcommerceBatches()
#3 /home/lucia/www/m1Developer/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncEcommerceBatchData(Object(Aoe_Scheduler_Model_Schedule))
#4 /home/lucia/www/m1Developer/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#5 /home/lucia/www/m1Developer/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#6 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#7 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#8 /home/lucia/www/m1Developer/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#9 /home/lucia/www/m1Developer/shell/scheduler.php(518): Mage::dispatchEvent('default', Array)
#10 /home/lucia/www/m1Developer/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#11 /home/lucia/www/m1Developer/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#12 {main}
```

**Comment by luciaebizmarts** [comment]
This issue is included in the [issue #846 ](https://github.com/mailchimp/mc-magento/issues/846)
