### ISSUE TITLE
Subscription fails when one store view is disabled with the API key in blank

### ISSUE THREAD

**Issue by luciaebizmarts** [mailchimp/mc-magento#867]
### Preconditions
1. Mailchimp for Magento development version, it doesn't happens in any released version.
2. Magento any version

### Steps to reproduce
1. Enable any scope to send ecommerce data leaving one store view disabled and with the field for the API key in blank.
2. Create a new user in Magento from the frontend subscribe the user in the newsletter.

### Expected result
1. Everything runs fine without errors.

### Actual result
1. The program fails when a registered user subscribe to the newsletter at 'My account->Newsletter' or after place the order, throwing the next error:
```
2019-01-30T13:35:39+00:00 DEBUG (7): #0 /home/lucia/www/m1Developer/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Helper/Data.php(3260): Ebizmarts_MailChimp_Helper_Data->getApi('1')
#1 /home/lucia/www/m1Developer/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Helper/Data.php(3294): Ebizmarts_MailChimp_Helper_Data->getInterest('1')
#2 /home/lucia/www/m1Developer/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Block/Customer/Newsletter/Index.php(48): Ebizmarts_MailChimp_Helper_Data->getInterestGroups('144', NULL, '1')
#3 /home/lucia/www/m1Developer/.modman/mc-magento/app/design/frontend/base/default/template/ebizmarts/mailchimp/customer/newsletter/index.phtml(3): Ebizmarts_MailChimp_Block_Customer_Newsletter_Index->getInterest()
#4 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lucia/www...')
#5 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#6 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#7 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#8 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#9 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('customer.form.n...', true)
#10 /home/lucia/www/m1Developer/app/design/frontend/base/default/template/customer/form/newsletter.phtml(39): Mage_Core_Block_Abstract->getChildHtml('customer.form.n...')
#11 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lucia/www...')
#12 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#13 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#14 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#15 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#16 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('customer_newsle...', true)
#17 /home/lucia/www/m1Developer/app/code/core/Mage/Page/Block/Html/Wrapper.php(52): Mage_Core_Block_Abstract->getChildHtml('', true, true)
#18 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Page_Block_Html_Wrapper->_toHtml()
#19 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#20 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#21 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#22 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#23 /home/lucia/www/m1Developer/app/design/frontend/rwd/default/template/page/2columns-left.phtml(59): Mage_Core_Block_Abstract->getChildHtml('content')
#24 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lucia/www...')
#25 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#26 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#27 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#28 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#29 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#30 /home/lucia/www/m1Developer/app/code/core/Mage/Newsletter/controllers/ManageController.php(60): Mage_Core_Controller_Varien_Action->renderLayout()
#31 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Newsletter_ManageController->indexAction()
#32 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#33 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#34 /home/lucia/www/m1Developer/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#35 /home/lucia/www/m1Developer/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#36 /home/lucia/www/m1Developer/index.php(83): Mage::run('', 'store')
#37 {main}
```

**Comment by luciaebizmarts** [comment]
Bug introduced with the enhancement **Add subscription option on order success page** closes #770
