### ISSUE TITLE
Illegal Blocktype: Ebizmarts_MailChimp_Block_Group_Types in app/Mage.php

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#915]
Receiving illegal blocktype in checkout success? or checkout after upgrade to latest

### Preconditions
M1934 and MC 1.1.15

### Steps to reproduce
Checkout order

### Expected result
No errors

### Actual result
Below is log

```
2019-03-15T07:33:50+00:00 ERR (3): 
Mage_Core_Exception: Ongeldig bloktype: Ebizmarts_MailChimp_Block_Group_Types in app/Mage.php:596
Stack trace:
#0 app/code/community/SafeMage/Plugin/Model/Plugin.php(35): Mage::throwException('Ongeldig blokty...')
#1 var/cache/plugins/Mage_Core_Model_Layout_Plugged.php(12): SafeMage_Plugin_Model_Plugin->aroundGetBlockInstance(Object(Mage_Core_Model_Layout_Plugged), Array)
#2 app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout_Plugged->_getBlockInstance('mailchimp/group...', Array)
#3 app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('mailchimp/group...', 'mailchimp.group...')
#4 app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('mailchimp/group...', 'mailchimp.group...')
#5 app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#6 app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#7 app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#8 app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#9 app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#10 app/code/core/Mage/Checkout/controllers/OnepageController.php(296): Mage_Core_Controller_Varien_Action->loadLayout()
#11 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->successAction()
#12 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('success')
#13 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#15 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#16 index.php(84): Mage::run('soc_nl', 'store')
#17 {main}
```

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This is solved at https://github.com/mailchimp/mc-magento/pull/884

Kind Regards.
